[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.22", features = [ "derive" ] }
futures = "0.3"
log = "0.4"
web-time = "1.1"
wgpu = "25.0"
winit = "0.30"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.4"

