[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23", features = [ "derive" ] }
futures = "0.3"
log = "0.4"
pollster = "0.4"
wgpu = "26.0"
winit = { path = "../../../winit/winit" }

