[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.22", features = [ "derive" ] }
futures = "0.3"
log = "0.4"
pollster = "0.4"
wgpu = "25.0"
winit = "0.30"

